### ISSUE TITLE
figure out how not to clip the thumbnails

### ISSUE THREAD

**Issue by jread-usgs** [USGS-OWI/owi-blog#20]
Either let us know what aspect ratio to use, or let that resize w/o clipping

![image](https://cloud.githubusercontent.com/assets/2349007/16165310/c5166a90-34a8-11e6-865f-18842050b034.png)

**Comment by mwernimont** [comment]
@ldecicco-USGS issues with this ticket have been taken care of with this PR #32

A few things, the box looks a little big for the content, but I left it that way since if you guys come up with a super long title that wraps even with my changes it'll push down the content and I don't want it jutting out of the div. A good idea would be to come up with a title text limit so I could make a make a smaller box and not worry about if the title will wrap or not. In any case the current box size should accommodate any title length you want.
